
DROP TABLE MYPLACE;


CREATE TABLE MYPLACE(
	MYID NUMBER PRIMARY KEY,
	PLACENAME VARCHAR2(1000) NOT NULL,
	PLACEADDR VARCHAR2(2000) NOT NULL,
	PLACEDATE DATE NOT NULL,
	THUMBS NUMBER
);


SELECT MYID, PLACENAME, PLACEADDR, PLACEDATE, THUMBS FROM MYPLACE;

